apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: 1tsmj/mjmjstudentmanagementrepo:latest
          ports:
            - containerPort: 8080
          env:
            - name: jdbc:mysql://localhost:3306/studentdb?createDatabaseIfNotExist=true
              value: jdbc:mysql://localhost:3306/studentdb
            - name: student-management
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: rootpassword
---
apiVersion: v1
kind: Service
metadata:
  name: student-management
spec:
  selector:
    app: student-management
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080   # Explicit NodePort
  type: NodePort
